{% set name = "readimc" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/readimc-{{ version }}.tar.gz
  sha256: dfa5268445e97674ca8213e7198416e28f44595b99c7cc55fecbdc8fc77ddf60

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - imageio
    - numpy
    - pandas
    - python >=3.8

test:
  imports:
    - readimc
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BodenmillerGroup/readimc
  summary: Read Imaging Mass Cytometry files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jwindhager
